### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by namangirdhar16** [web3community/start-here#106]
### Name

Naman

### Discord Username (if applicable)

n_m_n#2797

### Additional Context

Hi, i got to know about Web 3 community through twitter and hacktoberfest. I like the idea of decentralized technology and open source, web 3 meets both these preferences of mine. Moreover, I have just started open source and It would be a great oppurtunity to network and grow with people here, and contribute to something that has so much to offer.

**Comment by shuklaritvik06** [comment]
Welcome to Web3Community ✨
