### ISSUE TITLE
How to contribute to Web 3 if you can't code?

### ISSUE THREAD

**Issue by tommycaldwell** [web3community/start-here#112]
### Name

Tommy Caldwell

### Additional Context

Hi there, I have been interested in the future of Web 3 for a while now, but no matter how hard I try to learn coding, it simply isn't for me. I will never be a high-level coder. So how does an entrepreneur who has a strong history of leadership, management, and vision get involved in the future of the internet?

**Comment by shuklaritvik06** [comment]
Hey @tommycaldwell 👋🏼 ! Welcome to Web3Community ✨ Great to see that you want to contribute, and learn about web3 😄 ! You can join our [Discord Server](https://discord.gg/TSRwqx4K2v) :) We all are learning and growing together. You can join us there and learn web3 together 💙 You'll get to interact with some awesome folks there like @vinzvinci , @KukretiShubham , @krishguptadev , @Panquesito7 and @mkubdev

**Comment by mkubdev** [comment]
Hi @tommycaldwell ! Welcome here ! ✨ Development learning curve is high, but passion can lead you everywhere ⭐ Join us on the discord, we share content about web3 and we learning together.
