### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by abrahamalen** [web3community/start-here#123]
### Name

Alen Abraham

### Discord Username (if applicable)

Alen Abraham#3090

### Additional Context

I heard about the community in the GitHub daily updates and I was curious about web3, so suddenly I jumped.

**Comment by krishguptadev** [comment]
Welcome to the Community!

**Comment by abrahamalen** [comment]
> Welcome to the Community!

Thank You for the warm welcome @krishguptadev 
Looking forward to work and learn with you guys
