### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by marpit19** [web3community/start-here#125]
### Name

Arpit Mohapatra

### Discord Username (if applicable)

Asuna

### Additional Context

Just did my first contribution to **_web3 community_** and looking forward to doing more 🚀

**Comment by krishguptadev** [comment]
Welcome to the Community!

**Comment by marpit19** [comment]
> Welcome to the Community!

looking forward to contributing more!!

**Comment by mkubdev** [comment]
@marpit19 Noice!
