### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by jose-jimmy** [web3community/start-here#130]
### Name

Jose Jimmy

### Discord Username (if applicable)

Achilles#9993

### Additional Context

Hi, I am a CS undergrad currently exploring blockchain technology and  WEB 3 apps. I have a good understanding of blockchain and want to increase it into a developer perspective.  I just found this group active and hope to learn more from you guys. 😃

**Comment by krishguptadev** [comment]
Welcome to the community!
