### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by gaurtvin** [web3community/start-here#131]
### Name

Gaurav Pandey

### Discord Username (if applicable)

gaurtvin

### Additional Context

I meet web3community through @krishguptadev profile, I think this is the perfect place for learning and exploring web3 and its community. I want to join this community because as a NewBie in Web3.0 and Blockchain this community is going to help me a lot. 🌈

**Comment by krishguptadev** [comment]
Welcome to the community! Nice to know you got to know web3community from my profile 😄
