### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by phuoctung28** [web3community/start-here#166]
### Name

Nguyen Phuoc Tung

### Additional Context

I heard about web3 by chance, when my teacher introduced it to me in the computer science class. That's a big change of the web evolvement. However, while searching all around the Internet, I can't find much blogs, videos, or courses that have good quality, I just find a few from medium, some courses from udemy, and so on. When I read the repo about your community, I have to say "wow", it looks detailed. It is the path, the guideline that I want, or maybe for my friends who never heard about web3 before. I want to join to enhance my developer skill, study more about web3 and connect with people who engage in web3 like me ^^

**Comment by mkubdev** [comment]
Welcome here @phuoctung28 ! 👋🏻 ✨ Reach us on the [Discord server](https://discord.gg/gB3xb9XJ) !
