### ISSUE TITLE
[IDEA] Adding social media links of the community

### ISSUE THREAD

**Issue by unnikrishnan2002** [web3community/start-here#177]
### Description of the idea

It would be great if we add social media links of the community to the readme file so that people can find out easily

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unnikrishnan2002** [comment]
I would like to work on this

**Comment by shuklaritvik06** [comment]
> I would like to work on this

Assigning you this issue, you can use the image shields for the links :) https://shields.io/

**Comment by unnikrishnan2002** [comment]
> > I would like to work on this
> 
> Assigning you this issue, you can use the image shields for the links :) https://shields.io/

I will use the same image links used in the web3community readme as shields don't have all the social media badges.
