### ISSUE TITLE
Effective and attractive website

### ISSUE THREAD

**Issue by swati2603** [web3community/start-here#25]
### Description of the idea

I can make an effective and attractive website with functionalities and proper support. Users can submit their queries or we can add a chatbot too. Everyone can submit feedback. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KukretiShubham** [comment]
recreate the issue with invite template.

**Comment by vinzvinci** [comment]
I think Swati is proposing for our website. I will open this

**Comment by KukretiShubham** [comment]
Swati wanted to join Github org via this issue. So, I the suggested to use 'invitation template'.  
You are right. Glad you opened again.!

**Comment by vinzvinci** [comment]
I see. Swati already join after that.

**Comment by swati2603** [comment]
Thanks for assigning me.

**Comment by mkubdev** [comment]
You can clone [current website](https://github.com/web3community/web3community.github.io) and make a PR :)

**Comment by vinzvinci** [comment]
We can close this issue.

**Comment by swati2603** [comment]
@mkubdev Okay :)
