### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by sajjadcodes** [web3community/start-here#261]
### Name

sajjadcodes

### Additional Context

- [x] I was looking for web3 open-source resources.
- [x] WebXDAO focuses on future web technologies.
- [x] To learn about future technologies and share.

**Comment by shuklaritvik06** [comment]
Welcome Sajjad! You can checkout our blockchain [dev path](https://github.com/WebXDAO/blockchain-dev-path). You can also checkout our open issues! Hope you will have a good learning time here  :)
