### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by ishangupta-ds** [web3community/start-here#38]
### Name

ishangupta-ds

### Additional Context

I am a software engineer, a Blockchain, DeFi and  Dapps enthusiast. I found this community while exploring Blockchain based projects on GitHub, I like the dev ecosystem of this community and looking forward to collaborate on Dapps.

**Comment by vinzvinci** [comment]
Awesome! Welcome here!

**Comment by shuklaritvik06** [comment]
Welcome to the community! 🥳😄
