### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by NIKU-SINGH** [web3community/start-here#96]
### Name

Niku Singh

### Discord Username (if applicable)

kalm#1433

### Additional Context

Recently have been hearing a lot about blockchain and bitcoin. So I was looking for a community where I can find folks so that I am able to learn from them and collaborate on some projects.
I think this community can help me excel in my blockchain career as I am still a beginner so the environment that it provides would be really helpful.

**Comment by krishguptadev** [comment]
Welcome to this Community!
