### ISSUE TITLE
Please invite me to the community. I want to become part of this wonderful community.

### ISSUE THREAD

**Issue by neerajsingh869** [web3community/start-here#97]
### Name

Neeraj Kumar Singh

### Discord Username (if applicable)

iam_nks#4881

### Additional Context

I wanted to start learning Web 3 technologies simply because I have huge interest for Blockchain technology. During these times, I came across this repo which is fantastic and very recent, so wanted to become member of it in order to get help as well as provide help to others.

**Comment by krishguptadev** [comment]
Welcome to this Community!
